version: "3.8"

services:
  db_service:
    build:
      context: .
      dockerfile: ./db_service/Dockerfile
    environment:
      MONGO_INITDB_DATABASE: proc-rec-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data/dataset_engineer.json:/data/dataset_engineer.json
      - ./db_service/mongo_script.sh:/docker-entrypoint-initdb.d/mongo_script.sh
      - ./db_service/mongo_create_user.sh:/docker-entrypoint-initdb.d/mongo_create_user.sh

  model_training_service:
    build:
      context: .
      dockerfile: ./model_training_service/Dockerfile
    depends_on:
      - db_service
    volumes:
      - ./data:/data
